
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package camran.atributos_sintetizados.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ID = 5;
  public static final int MULT = 2;
  public static final int error = 1;
  public static final int NUMBER = 4;
  public static final int ADD = 3;
  public static final int CLOSE_PARENTHESIS = 7;
  public static final int OPEN_PARENTHESIS = 6;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MULT",
  "ADD",
  "NUMBER",
  "ID",
  "OPEN_PARENTHESIS",
  "CLOSE_PARENTHESIS"
  };
}

